### ISSUE TITLE
Uncoference event, idea for community discussion 

### ISSUE THREAD

**Issue by sunnivin** [nordic-rse/conference-contributions#1]
### It is a:
- [ ] Short talk (10 minutes including discussion)
- [ ] Longer talk (30 minutes including discussion)
- [x] Discussion (up to 80 minutes)
- [ ] Demonstration (up to 80 minutes)
- [ ] Workshop (up to 80 minutes)
- [ ] Something else (up to 80 minutes)

### Do you need help?
- [x] I would like someone to help me plan the contribution

### Would you be comfortable if your event was live-streamed/recorded?
- [x] Yes
- [ ] No

### Give a short description of your contribution:
As an RSE in a team of scientists, I feel that I quickly fall into the "git-evangelist" role. I think it would be super interesting, and useful, to have a discussion about different techniques and experiences for how to take this role in a positive sense. 

In a broader context, this question is related to how to successfully recommend "good enough" software engineering practices to colleagues with less technical competence than yourself?"

**Comment by rkdarst** [comment]
Hello!

Thanks for suggesting this talk.  We are getting ready for next week and are looking forward to everything.

We've prepared some hints for presenters, which may or may not be useful to you: https://hackmd.io/bPTVDi2wRl2CRfJ2YGMwrQ .  You requested some help preparing, and there are some hints in there about how to get feedback.  That says more, but the main options are to ask on Nordic-RSE chat (recommended), but if you want you could email me personally at rkd@zgib.net and we can take a look.

If you have any more questions about preparing, please let me know.  Please register for the unconference if you haven't already, so you can get the other practical information we'll be sending soon: https://nordic-rse.org/events/2021-online-unconference/ .

**Comment by rkdarst** [comment]
A Zoom mentoring session for submissions will be held at https://uit.zoom.us/j/63566985867 at 13:00 CEST on Thursday 2021-06-24.  We hope to see you there!
