### ISSUE TITLE
Unconference event: Development frameworks for Research Software

### ISSUE THREAD

**Issue by harivyasi** [nordic-rse/conference-contributions#11]
### It is a:
- [ ] Short talk (10 minutes including discussion)
- [ ] Longer talk (20 minutes including discussion)
- [x] Discussion (up to 70 minutes)
- [ ] Demonstration (up to 70 minutes)
- [ ] Workshop (up to 70 minutes)
- [ ] ReproHack (up to 70 minutes)
- [ ] Something else (up to 70 minutes)

### Do you need help?
- [x] I would like someone to help me plan the contribution

### Would you be comfortable if your event was recorded?
- [x] Yes
- [ ] No

### Please indicate on which day(s) the contribution can happen (tick both if you don't mind which one):
- [ ] June 29
- [x] June 30

### Give a short description of your contribution:

Industrial scale software development relies heavily on development frameworks/methodologies such as Agile and Scrum. What are some in-house approaches/good-practices that RSEs have developed along the same lines? Can these be documented and formalized for wider dissemination (e.g. inducting new RSEs) and can they be tested for effectiveness?

Some wider/alternative points of discussion include:
- How RSE teams can use a single workflow to eliminate the lottery/bus factor
- Is formalization of workflow necessary (after all the Researcher component of an RSE loves freedom provided by the academic setting)
- A day in the life of a typical RSE (whatever typical is): how you manage software development workflow

(If someone who has worked in industry can bring their perspective e.g. pros and cons of using Agile/Scrum etc., that can greatly increase the scope and utility of this discussion.)

**Comment by rkdarst** [comment]
Hello!

Thanks for suggesting this talk. We are getting ready for next week and are looking forward to everything.

We've prepared some hints for presenters, which may or may not be useful to you: https://hackmd.io/bPTVDi2wRl2CRfJ2YGMwrQ . You requested some help preparing, and there are some hints in there about how to get feedback. That says more, but the main options are to ask on Nordic-RSE chat (recommended), but if you want you could email me personally at rkd@zgib.net and we can take a look.

If you have any more questions about preparing, please let me know. Please register for the unconference if you haven't already, so you can get the other practical information we'll be sending soon: https://nordic-rse.org/events/2021-online-unconference/ .

A Zoom mentoring session for submissions will be held at https://uit.zoom.us/j/63566985867 at 13:00 CEST on Thursday 2021-06-24.  We hope to see you there!
