### ISSUE TITLE
Review of 2021-2022 for Nordic RSE

### ISSUE THREAD

**Issue by rantahar** [nordic-rse/conference-contributions#14]
### It is a:
- [x] Short talk (10 minutes including discussion)
- [x] Longer talk (20 minutes including discussion)
- [ ] Discussion (up to 70 minutes)
- [ ] Demonstration (up to 70 minutes)
- [ ] Workshop (up to 70 minutes)
- [ ] ReproHack (up to 70 minutes)
- [ ] Something else (up to 70 minutes)

### Do you need help?
- [ ] I would like someone to help me plan the contribution

### Would you be comfortable if your event was recorded?
- [x] Yes
- [ ] No

### Please indicate on which day(s) the contribution can happen (tick both if you don't mind which one):
- [x] August 16
- [ ] August 17

### Give a short description of your contribution:

Essentially an introduction to Nordic RSE, focusing on what we have done in the past year.
 - Seminar series
 - Coffee breaks
 - December AOC run
 - ...
 - Also mention related projects, such as CR

**Comment by lucaferranti** [comment]
Hi @rantahar :wave:,

thank you for your submission and apologies for the slow follow-up.

We are approaching the unconference and I would like to share some information and ask a few things

1. The schedule is now on the webpage: https://nordic-rse.org/events/2022-online-unconference/#how-it-works It will be on 18th October and 19th October, **are you still willling to participate?**
2. Would you like to deliver your talk on the unconference slot on the first day, that is **October 18th 14:50 CET**?
3. Are you ok with the title and abstract being published on the webpage?
4. If you haven't already, make sure to [register for the unconference](https://indico.neic.no/event/232/)

Thank you for your contribution and if you have any questions, feel free to ping me

/Luca

**Comment by rantahar** [comment]
Already in the agenda, closing
