### ISSUE TITLE
Keep your code alive - lessons from the QuTiP project

### ISSUE THREAD

**Issue by quantshah** [nordic-rse/conference-contributions#3]
### It is a:
- [ ] Short talk (10 minutes including discussion)
- [x] Longer talk (20 minutes including discussion)
- [ ] Discussion (up to 70 minutes)
- [ ] Demonstration (up to 70 minutes)
- [ ] Workshop (up to 70 minutes)
- [ ] ReproHack (up to 70 minutes)
- [ ] Something else (up to 70 minutes)

### Do you need help?
- [x] I would like someone to help me plan the contribution

### Would you be comfortable if your event was recorded?
- [x] Yes
- [ ] No

### Please indicate on which day(s) the contribution can happen (tick both if you don't mind which one):
- [x] June 29
- [ ] June 30

### Give a short description of your contribution:

The Quantum Toolbox in Python (QuTiP) is a widely used tool for simulating quantum physics. In this talk we will discuss QuTiP's journey from a Python project started by two researchers, to a community of developers and users spread all across the globe. The talk will focus on building an open-source community and how QuTiP was kept alive through contributions from the community, Google summer of Code and different academic and non-academic funding opportunities.

**Comment by bast** [comment]
Thanks so much! Adding it to the program: https://github.com/nordic-rse/nordic-rse.github.io/pull/241

**Comment by quantshah** [comment]
Hi, I need to make a change in the abstract. The project was started by two postdocs and not Ph.D. students. I am sorry for the mistake but I had to trace the information back to the group where it started. Could you please update the abstract on the website? 

I have updated it here.

**Comment by bast** [comment]
Yes. Working on it ...

**Comment by quantshah** [comment]
It is updated now. Thank you so much and apologies for the trouble.

**Comment by bast** [comment]
Ah. Somebody else did it. Good :-)

**Comment by rkdarst** [comment]
Hello!

Thanks for suggesting this talk.  We are getting ready for next week and are looking forward to everything.

We've prepared some hints for presenters, which may or may not be useful to you: https://hackmd.io/bPTVDi2wRl2CRfJ2YGMwrQ .  You requested some help preparing, and there are some hints in there about how to get feedback.  That says more, but the main options are to ask on Nordic-RSE chat (recommended), but if you want you could email me personally at rkd@zgib.net and we can take a look.

If you have any more questions about preparing, please let me know.  Please register for the unconference if you haven't already, so you can get the other practical information we'll be sending soon: https://nordic-rse.org/events/2021-online-unconference/ .

**Comment by rkdarst** [comment]
A Zoom mentoring session for submissions will be held at https://uit.zoom.us/j/63566985867 at 13:00 CEST on Thursday 2021-06-24.  We hope to see you there!

**Comment by quantshah** [comment]
Thanks. I will be there.
