### ISSUE TITLE
Unconference event: how to make Research Software Hour more visible and useful

### ISSUE THREAD

**Issue by bast** [nordic-rse/conference-contributions#4]
### It is a:
- [x] Discussion (30-35 minutes, can be more)

### Do you need help?
- [x] I would like someone to help me plan the contribution

### Would you be comfortable if your event was recorded?
- [x] Yes
- [ ] No

### Please indicate on which day(s) the contribution can happen (tick both if you don't mind which one):
- [x] June 29
- [x] June 30

### Give a short description of your contribution:

With Anne and Richard and soon hopefully others we are running the [Research Software Hour](https://researchsoftwarehour.github.io/) Twitch stream. This is fun and I believe we have a number of very useful recordings but we would like to make it more useful to the community and also reach a wider community, both as watchers but also as contributors.

In this discussion session we could collect ideas on what to improve in format and announcement and also discuss how we can involve more people to contribute, share, and discuss on stream with us.

**Comment by rkdarst** [comment]
Hello!

Thanks for suggesting this talk.  We are getting ready for next week and are looking forward to everything.

We've prepared some hints for presenters, which may or may not be useful to you: https://hackmd.io/bPTVDi2wRl2CRfJ2YGMwrQ .  You requested some help preparing, and there are some hints in there about how to get feedback.  That says more, but the main options are to ask on Nordic-RSE chat (recommended), but if you want you could email me personally at rkd@zgib.net and we can take a look.

If you have any more questions about preparing, please let me know.  Please register for the unconference if you haven't already, so you can get the other practical information we'll be sending soon: https://nordic-rse.org/events/2021-online-unconference/ .

**Comment by rkdarst** [comment]
A Zoom mentoring session for submissions will be held at https://uit.zoom.us/j/63566985867 at 13:00 CEST on Thursday 2021-06-24.  We hope to see you there!
