### ISSUE TITLE
Unconference event: Myths and misconceptions about Research Software development in Academia

### ISSUE THREAD

**Issue by annefou** [nordic-rse/conference-contributions#5]
### It is a:
- [ ] Short talk (10 minutes including discussion)
- [ ] Longer talk (20 minutes including discussion)
- [x] Discussion (up to 70 minutes)
- [ ] Demonstration (up to 70 minutes)
- [ ] Workshop (up to 70 minutes)
- [ ] ReproHack (up to 70 minutes)
- [ ] Something else (up to 70 minutes)

### Do you need help?
- [ ] I would like someone to help me plan the contribution

### Would you be comfortable if your event was recorded?
- [x] Yes
- [ ] No

### Please indicate on which day(s) the contribution can happen (tick both if you don't mind which one):
- [x] June 29
- [x] June 30

### Give a short description of your contribution:

The goal is to explore and discuss myths and misconceptions about research software development in academia and how these myths and misconceptions are hindering the organization and recognition of Research software Engineers in the Nordics. To initiate the discussion, we will provide a few examples such as:
- Development of Research Software is not research.
- Research software is any code that has been written by a scientist
- Anyone who has written (or even looked) at 3 lines of code is a qualified Research Software Engineer
- Software is data so FAIR software==FAIR data

**Comment by bast** [comment]
:100:

**Comment by rkdarst** [comment]
Hello!

Thanks for suggesting this talk.  We are getting ready for next week and are looking forward to everything.

We've prepared some hints for presenters, which may or may not be useful to you: https://hackmd.io/bPTVDi2wRl2CRfJ2YGMwrQ .

If you have any more questions about preparing, please let me know.  Please register for the unconference if you haven't already, so you can get the other practical information we'll be sending soon: https://nordic-rse.org/events/2021-online-unconference/ .
