### ISSUE TITLE
Unconference event: Publishing software papers

### ISSUE THREAD

**Issue by lucaferranti** [nordic-rse/conference-contributions#6]
### It is a:
- [ ] Short talk (10 minutes including discussion)
- [ ] Longer talk (20 minutes including discussion)
- [x] Discussion (up to 70 minutes)
- [ ] Demonstration (up to 70 minutes)
- [ ] Workshop (up to 70 minutes)
- [ ] ReproHack (up to 70 minutes)
- [ ] Something else (up to 70 minutes)

### Do you need help?
- [x] I would like someone to help me plan the contribution

### Would you be comfortable if your event was recorded?
- [x] Yes
- [ ] No

### Please indicate on which day(s) the contribution can happen (tick both if you don't mind which one):
- [x] June 29
- [x] June 30

### Give a short description of your contribution:

Publications are the currency for researchers and number and distribution of publications can often be a tie-breaker for getting fundings, so let's talk about where to publish research software papers.

A few inputs to start the discussion
- What are the forums that accept research software papers? There are e.g. JOSS, JORS, softwareX, do you know others?
- What to publish there? When is a research software "good enough" to be published in a journal?
- How do these journals compare to traditional journals? When should you choose a "traditional" forum and when a software forum, what are the advantages and disadvantages of each?
- How are these journals ranked compared to other ones? Some countries (e.g. Finland and Norway) have a ranking system of publication forums. How are these forums ranked? How should they be ranked?
- Is there enough awareness of these forums? Are all RSEs and researchers aware of these forums and related issues? What can we do to increase awareness (if needed)?

**Comment by bast** [comment]
:100:

**Comment by rkdarst** [comment]
Hello!

Thanks for suggesting this talk.  We are getting ready for next week and are looking forward to everything.

We've prepared some hints for presenters, which may or may not be useful to you: https://hackmd.io/bPTVDi2wRl2CRfJ2YGMwrQ .  You requested some help preparing, and there are some hints in there about how to get feedback.  That says more, but the main options are to ask on Nordic-RSE chat (recommended), but if you want you could email me personally at rkd@zgib.net and we can take a look.

If you have any more questions about preparing, please let me know.  Please register for the unconference if you haven't already, so you can get the other practical information we'll be sending soon: https://nordic-rse.org/events/2021-online-unconference/ .

**Comment by rkdarst** [comment]
A Zoom mentoring session for submissions will be held at https://uit.zoom.us/j/63566985867 at 13:00 CEST on Thursday 2021-06-24.  We hope to see you there!
