### ISSUE TITLE
Unconference Event: Getting funding for software projects

### ISSUE THREAD

**Issue by tpfau** [nordic-rse/conference-contributions#8]
### Title of the contribution:
Getting funding for software projects

### It is a:
- [ ] Short talk (10 minutes including discussion)
- [ ] Longer talk (20 minutes including discussion)
- [X] Discussion (up to 70 minutes)
- [ ] Demonstration (up to 70 minutes)
- [ ] Workshop (up to 70 minutes)
- [ ] ReproHack (up to 70 minutes)
- [ ] Something else (up to 70 minutes)

### Do you need help?
- [X] I would like someone to help me plan the contribution

### Would you be comfortable if your event was recorded?
- [X] Yes
- [ ] No

### Please indicate on which day(s) the contribution can happen (tick both if you don't mind which one):
- [X] June 29
- [X] June 30

### Give a short description of your contribution:
Funding for software projects is often an issue, as they don't necessarily immediately lead to a scientific advance but can facilitate other peoples research. At the same time software tools are often cited and clearly do contribute significantly to the conducted research but it seems difficult to find funding for developing, and particularly maintaining software.

Possible discussion starters:

I imagine two fields of discussion:
A: Where and how to get funding?
- What funding sources are available to software projects?
  - For the improvement of existing projects
  - For new projects
- How did you get funding for your software project?
- Getting funding for a software project by embedding it into larger proposals.
  - How to best go about getting funding for software into a larger grant proposal?
  - Which calls are more likely to support these kind of mixed science/software approaches.

B: How can we get more funding for scientific software?
- Who makes the decisions for public or industry funding of software projects, and could be approached to lobby for more funding?
- What arguments are there for funding open source/academic software projects?
- What arguments are there against public funding of software projects? (In order to be able to address those arguments)

I hope that we can in the end generate some document that
1: Lists potential sources of funding (from small scale 2-3 month student projects) to larger scale funding. 
and 
2: Offers arguments for public funding software projects and discusses counter-arguments which can be used as a starting point to help people argue for more funding with their respective local funding agencies. 

HackMD at:
https://hackmd.io/@tpfau/Funding

**Comment by bast** [comment]
Thanks for the great suggestion! Looking forward!

**Comment by tpfau** [comment]
Admittedly, I don't have a lot of ideas where to look and am hoping for either some input myself or for getting some idea on how to try and talk with decision makers that this type of "research support" needs to be funded directly, and not by getting software companies to sell stuff and paying for that...

**Comment by rkdarst** [comment]
Hello!

Thanks for suggesting this talk.  We are getting ready for next week and are looking forward to everything.

We've prepared some hints for presenters, which may or may not be useful to you: https://hackmd.io/bPTVDi2wRl2CRfJ2YGMwrQ .  You requested some help preparing, and there are some hints in there about how to get feedback.  That says more, but the main options are to ask on Nordic-RSE chat (recommended), but if you want you could email me personally at rkd@zgib.net and we can take a look.

If you have any more questions about preparing, please let me know.  Please register for the unconference if you haven't already, so you can get the other practical information we'll be sending soon: https://nordic-rse.org/events/2021-online-unconference/ .

**Comment by rkdarst** [comment]
A Zoom mentoring session for submissions will be held at https://uit.zoom.us/j/63566985867 at 13:00 CEST on Thursday 2021-06-24.  We hope to see you there!

**Comment by tpfau** [comment]
@rkdarst Thanks again for organizing the mentoring session. I updated the description with some additional points for the discussion and potential products of the discussion so that this can be integrated into the schedule. Should I set up a HackMD for the session myself and just give you the link for the schedule?

**Comment by tpfau** [comment]
I created a HackMD now. Lets see if it works :)
