### ISSUE TITLE
Unconference event: Developing the Nordic RSE

### ISSUE THREAD

**Issue by rantahar** [nordic-rse/conference-contributions#9]
### It is a:
- [ ] Short talk (10 minutes including discussion)
- [ ] Longer talk (20 minutes including discussion)
- [x] Discussion (up to 70 minutes)
- [ ] Demonstration (up to 70 minutes)
- [x] Workshop (up to 70 minutes)
- [ ] ReproHack (up to 70 minutes)
- [ ] Something else (up to 70 minutes)

### Do you need help?
- [ ] I would like someone to help me plan the contribution

### Would you be comfortable if your event was recorded?
- [x] Yes
- [ ] No

### Please indicate on which day(s) the contribution can happen (tick both if you don't mind which one):
- [ ] June 29
- [x] June 30

### Give a short description of your contribution:

The purpose of this workshop / discussion is is to talk about the activities of the Nordic RSE and especially what we should do in the future. As an outcome, we will add a page to the Nordic RSE website with planned actions the participants believe will benefit research software engineers in the Nordics.

This could include setting a date for the first association members meeting and working on the statutes of the association.

**Comment by rkdarst** [comment]
Hello!

Thanks for suggesting this talk.  We are getting ready for next week and are looking forward to everything.

We've prepared some hints for presenters, which may or may not be useful to you: https://hackmd.io/bPTVDi2wRl2CRfJ2YGMwrQ .

If you have any more questions about preparing, please let me know.  Please register for the unconference if you haven't already, so you can get the other practical information we'll be sending soon: https://nordic-rse.org/events/2021-online-unconference/ .

**Comment by rkdarst** [comment]
A Zoom mentoring session for submissions will be held at https://uit.zoom.us/j/63566985867 at 13:00 CEST on Thursday 2021-06-24.  We hope to see you there!
